### ISSUE TITLE
Json pretty print format

### ISSUE THREAD

**Issue by mojtabaimani** [kuberise/show-env#2]
# **Pretty print output json and codespace setup**
I would like to print json of environment variables in a pretty print format to be more readable on the screen. 

## **Why**: 
User can see all environment variables without scrolling horizontally. 

## **Acceptance Criteria**: 
1. Print the environment variable json in pretty print format
2. Run the application in codespace

## **Task:**

- [ ] Setup a base codespace environment capable of running python
- [ ] Install the required extensions and features 
- [ ] Configure the codespace to enable debugging with support for breakpoints.
- [ ] Ensure port forwarding is enabled and tested to allow in-browser application runs.
- [ ] Commit the codespace configuration to the main repository to standardize the development environment across new codespaces.
